### ISSUE TITLE
How to identify lying endpoints?

### ISSUE THREAD

**Issue by thomas-fossati** [britram/draft-trammell-quic-spin#10]
Last para of the Security and Privacy Consideration section: we say it is easy to verify that an endpoint is lying.  But, practically, how would you do that?  ISTM that you'd need to take the suspect implementation(s) and make them exchange data on a strictly controlled end-to-end path.  How is that achievable in the general case?

BTW, I agree the incentive to lie is low, while there is a mild incentive to be truthful because providing the signal is a) very cheap and b) could be directly useful to the endpoints (e.g., the net regulation enforcement use case).

**Comment by britram** [comment]
Actually, I think it's easier than I wrote.

Assume you have a server that wants its e22 latency to look lower than it is (because latency on the content provider's network is higher than the SLA says it should be). So, it will basically anticipate edges in the spin bit it sees from the client, and instead of echoing, will do a flip itself somewhat before the client flip arrives, then will ignore the client flip when it receives it. (We should probably define the algorithm for the server to run given a real rtt X and a target exposed RTT X' but maybe that doesn't need to be in this doc).

If you assume the server *always* drives its observable RTT to a given X', then you can just connect with a client you know to be honest, and compare the client's RTT estimate based on the ACK streams with the spinbit latency. Of course, the server could also pre-ack streams, but that's pretty risky in terms of breaking the transport's state. 

If the client and server collude to activate the server's edge anticipation, or worse, if the client cooperates, then you need to get fancy with statistical inference; i.e. look at different sub-aggregates sharing the same path and look for covariance. But I think we should consider the "two colluding endpoints sharing a secret channel" problem to be out of scope, because if you're going to that length to lie about an SLA, it's a Volkswagen-level incident when you finally get caught.

**Comment by thomas-fossati** [comment]
You got my point which was sort of implicit: from the point of view of a passive on-path observer QUIC *is* that secret channel allowing two parties to collude to get this kind of subversion :-)

**Comment by britram** [comment]
Yep. We might even want to point out (prove?) that preventing two parties who have an openly secret channel (i.e. not even a side channel they have to try to hide) from redefining the meaning of any bit in a wire image that is not used for forwarding is impossible and therefore a non-goal.

Actually, that belongs in my wire image draft, instead.

**Comment by thomas-fossati** [comment]
Seems like an useful thing to do to me - at the cost of stating the obvious.  

Header encryption is the enabler for permission-less innovation, and this is clear to everybody, I guess. So, the ability to freely redefine the semantics of nearly everything (as you say, everything but stuff that is instrumental to packet forwarding) is a first order / wanted consequence of this strategy.  The second-order effect that maybe is not immediate (or perhaps it is just purposely ignored) is that this same shift impacts the trust model from the network perspective:  it is now also impossible to "Доверяй, но проверяй" because the ability to verify has been drowned in the same water that has drastically reduced the risk to ossify...

**Comment by britram** [comment]
Added some text here to point out the known-honest client case, and pointed to the more pessimistic language in wire-image, so I think we're done.
