### ISSUE TITLE
Virtual AQM use case

### ISSUE THREAD

**Issue by britram** [britram/draft-trammell-quic-spin#4]
@ihlar, you mentioned (I think in Paris) that some AQMs use end-to-end RTT based flow classification for RTT fairness purposes; could you write a paragraph or two about this for a new subsection of section 4?

**Comment by ihlar** [comment]
Working on it today.

**Comment by ihlar** [comment]
Ah sorry, that´s a different case than the one I´m writing about. 
What we have built is a sort of "backup" AQM. Basically, large amounts of base-stations out in the wild don´t have proper AQM enabled. By deploying a virtual AQM in the network that monitors flows and react on flows that are determined to create congestion we manage to reduce a lot of buffer bloat experienced in RAN:s.
I guess for the case you are describing handshake RTT would many times be sufficient, the spin bit would of course improve things since path changes etc can occur. 
The first case we have both data and implementation experience from. But for the RTT fairness case I´m not sure how much things improve compared to simply using fq.

**Comment by britram** [comment]
Okay, but this is what you were discussing at the Paris interim, yes? Have changed title to compensate; text looks good.
