### ISSUE TITLE
Greasing the Spin Bit

### ISSUE THREAD

**Issue by britram** [britram/draft-trammell-quic-spin#7]
per a discussion with DKG in Singapore, we might want to add methods for greasing the spin bit to ensure that its meaning does not ossify, and that gating access on a valid spin bit signal is not a useful strategy for even an evil ISP. 

The simplest one is as follows: each server will refuse to spin its bit on a per-flow basis with a given probability _p_, instead leaving it stuck to a randomly chosen value, 0 or 1.  The client then ends up leaving its bit stuck to the opposite, or can detect this condition and also choose a randomly chosen stuck value.

I'm personally less convinced of the magic properties of grease than the WG seems to be, because it has a very particular middlebox-developer "threat model" in mind. But if we want to grease this so that we can (tell ourselves that we can) use the same bit for something other than spin in the future, this would be the way to do it.

**Comment by ihlar** [comment]
Sounds like the most sensible way to do the greasing so that it´s not confused for something meaningful. 
The big question is what value of _p_ is sufficiently high to discourage evil ISP-stuff, but low enough for proper use. Naturally, I would like _p_ to be as low as possible, but I suppose the rest of the WG would have different opinions.

**Comment by britram** [comment]
Talking about this in Singapore, I chose p as 0.125 (literally, "roll 1d8, if you roll a 1, no spin for you".) That was more of a random joke than anything else, but thinking about it a bit more it's probably not that wrong. 1e-3 or less often will be seen as an error (if a frequent one), not an intentional protocol feature. Comparing to other things that occasionally don't work: UDP blockage or impairment per path is p ≅ 0.03-0.06 and we engineer for that in QUIC, whereas p ≅ 0.2 - 0.5 for IPv6 DO headers in the Internet and we think of those as not working at all.

So 0.06 < p < 0.2 seams reasonable.

**Comment by thomas-fossati** [comment]
Congestion levels, routes, etc. fluctuate in ways that are not predictable, and so does latency between two fixed QUIC endpoints.
For example, let's say my wireless AP has a 10 minutes' hiccup that makes it drain its queues slower than usual - btw, I'm bringing this up because it's just happened :-)
It'd be foolish for an ISP to drop my QUIC flows based on the fact that my RTTs to youtube are now higher than usual, simply because of the sheer number of false negatives it'd get by setting an arbitrary threshold.
I'd say on the contrary that greasing MUST NOT be done by the endpoints because it erodes confidence in the veracity of the signal.

**Comment by britram** [comment]
closed by #14
